# Generated by Django 5.2.16 on 2026-08-10 20:07

import concurrency.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0033_alter_occurrence_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "version",
                    concurrency.fields.IntegerVersionField(
                        default=0, help_text="version number of the record", verbose_name="Version"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="Record last update time", verbose_name="Last updated"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="Record creation time", verbose_name="Created"),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Member custom fields for this application",
                        verbose_name="Custom fields",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Membership",
                "verbose_name_plural": "Application Memberships",
            },
        ),
        migrations.AddField(
            model_name="channel",
            name="preferred",
            field=models.BooleanField(
                default=False,
                help_text="use this channel as default for its protocol in its scope",
                verbose_name="preferred",
            ),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("preferred", True), ("project__isnull", True)),
                fields=("organization", "protocol"),
                name="bitcaster_channel_org_protocol_preferred",
            ),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("preferred", True)),
                fields=("organization", "project", "protocol"),
                name="bitcaster_channel_org_project_protocol_preferred",
            ),
        ),
        migrations.AddField(
            model_name="applicationmembership",
            name="application",
            field=models.ForeignKey(
                help_text="application the user is member of",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="bitcaster.application",
                verbose_name="Application",
            ),
        ),
        migrations.AddField(
            model_name="applicationmembership",
            name="user",
            field=models.ForeignKey(
                help_text="member user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="applicationmembership",
            unique_together={("user", "application")},
        ),
    ]
