# Generated by Django 5.2.16 on 2026-08-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitcaster", "0034_applicationmembership_channel_preferred_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmembership",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Mirrors the client application 'active' state for the user. "
                "If unchecked the user receives no notifications for this application",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="applicationmembership",
            name="enable_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Whether the user receives notifications for this application "
                "(effective only when active and not locked)",
                verbose_name="enable notifications",
            ),
        ),
        migrations.AddField(
            model_name="applicationmembership",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text="Managed only via the admin. "
                "If checked no notification is sent to the user for this application",
                verbose_name="locked",
            ),
        ),
    ]
